name: env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - codetiming
  - googleapis-common-protos
  - gdown
  - hydra-core
  - numpy
  - pip
  - python-json-logger
  - pytorch=2.0.1
  - torchvision>=0.15.2
platforms:
  - linux-64
