name: env
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - codetiming
  - cuda-toolkit
  - googleapis-common-protos
  - gdown
  - hydra-core
  - numpy
  - pip
  - python-json-logger
  - pytorch=2.1.1=py3.9_cuda12.1_cudnn8.9.2_0
  - torchvision>=0.16.0
platforms:
  - linux-64
