_target_: facetorch.analyzer.predictor.FacePredictorMediapipe

downloader:
  _target_: facetorch.downloader.DownloaderGDrive
  file_id: 16gNFQdEH2nWvW3zTbdIAniKIbPAp6qBA
  path_local: opt/facetorch/models/torchscript/predictor/align/1/model.pt # str

device:
  _target_: torch.device
  type: ${analyzer.device} # str

preprocessor:
  _target_: facetorch.analyzer.predictor.pre.PredictorPreProcessor
  transform: None
  device: 
    _target_: torch.device
    type: ${analyzer.predictor.align.device.type}
  optimize_transform: false
  reverse_colors: False # bool

postprocessor:
  _target_: facetorch.analyzer.predictor.post.PostEmbedder
  transform: None
  device: 
    _target_: torch.device
    type: ${analyzer.predictor.align.device.type}
  optimize_transform: ${analyzer.optimize_transforms}
  labels: ["abstract"] # List

