defaults:
  - analyzer: default.yaml
  - analyzer/reader: default.yaml
  - analyzer/detector: retinaface.yaml
  - analyzer/unifier: img_380.yaml
  - analyzer/predictor/embed: r50_vggface_1m.yaml
  #- analyzer/predictor/verify: adaface_ir101_webface12m.yaml
  - analyzer/predictor/fer: efficientnet_b2_8.yaml
  - analyzer/predictor/au: open_graph_swin_base.yaml
  - analyzer/predictor/va: elim_al_alexnet.yaml
  #- analyzer/predictor/deepfake: efficientnet_b7.yaml
  #- analyzer/predictor/align: synergy_mobilenet_v2.yaml
  #- analyzer/utilizer/align: lmk3d_mesh_pose.yaml
  - analyzer/predictor/align: mediapipe_last.yaml
  - analyzer/utilizer/align: mediapipe_lmk_pose_blend.yaml
  - analyzer/utilizer/draw_boxes: torchvision_boxes.yaml
  - analyzer/utilizer/draw_landmarks: torchvision_keypoints.yaml
  - analyzer/utilizer/draw_headpose: cv2_headpose.yaml
  - analyzer/utilizer/draw_text: torchvision_text.yaml
  - analyzer/utilizer/save: image_saver.yaml
  - analyzer/logger: json_format.yaml
  - _self_

main:
    sleep: 3

debug: true

#path_image: /idiap/temp/pvuillecard/libs/facetorch_extra/data/input/test2.jpg # str
#path_image: /idiap/temp/pvuillecard/libs/facetorch_extra/datasets/DFEW/examples/11205/frame0175.png # str
path_image: /idiap/temp/pvuillecard/libs/facetorch_extra/datasets/DFEW/examples/11205
batch_size: 4 # int
fix_img_size: False # bool
return_img_data: True # bool
include_tensors: True # bool
#path_output: /idiap/temp/pvuillecard/libs/facetorch_extra/data/output/test2_v2.png # Optional[str]
#path_output: /idiap/temp/pvuillecard/libs/facetorch_extra/data/output/tframe0175.png # Optional[str]
path_output: ${path_image}_outputv3
