
_target_: facetorch.analyzer.utilizer.draw.TextDrawerTorch
transform: None
device:
  _target_: torch.device
  type: ${analyzer.device} # str
optimize_transform: False
text_output: 
 - fer
 - va
 - au